# Generated by Django 4.2.4 on 2024-02-26 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='end_time',
            field=models.TimeField(default=1, verbose_name='End time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.room', verbose_name='Operation room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='start_time',
            field=models.TimeField(default=1, verbose_name='Start time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='booked',
            field=models.BooleanField(default=False, verbose_name='Is booked'),
        ),
        migrations.AddField(
            model_name='room',
            name='patient',
            field=models.ManyToManyField(blank=True, to='main.patient', verbose_name='Patient'),
        ),
        migrations.AlterUniqueTogether(
            name='operation',
            unique_together={('date', 'start_time', 'room')},
        ),
    ]
