# Generated by Django 4.2.4 on 2024-02-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_operation_end_time_operation_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateTimeField(verbose_name='Operation date'),
        ),
    ]
