# Generated by Django 4.2.4 on 2024-02-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(verbose_name='Operation date'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
